title: Matteo Lepur
position: Ph.D. Student
affiliation: University of British Columbia
email: matteolepur@stat.ubc.ca
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/matteolepur
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
